account/urls.py
from django.conf.urls import url 
from django.contrib.auth import views as auth_views


from . import views 

urlpatterns = [
				url(r'^login/$', auth_views.login, name = 'login'),
				url(r'^logout/$', auth_views.logout, name = 'logout'),
				url(r'^logout-then-login/$', auth_views.logout_then_login, name = 'logout-then-login'),
				url(r'^register/$', views.register, name = 'register'),
				]

todo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('todo_app.urls', namespace = 'todo', app_name = 'todo')),
    url(r'^account/', include('account.urls', namespace = 'account', app_name = 'account')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

todo_app/urls.py
from django.conf.urls import url 

from . import views

urlpatterns = [
				url(r'^$', views.home_page, name = 'home'),
				url(r'^(?P<todo_id>[0-9]+)/$', views.todo_detail, name = 'detail'),
				url(r'^post/$', views.post_todo, name = 'post'),
				url(r'^delete/(?P<todo_id>[0-9]+)/$', views.delete_todo, name = 'delete'),
				url(r'^edit/(?P<todo_id>[0-9]+)/$', views.edit_todo, name = 'edit'),
				]

account/models.py
from django.db import models

# Create your models here.

todo_app/models.py
from django.db import models

from django.core.urlresolvers import reverse

class Todo(models.Model):
	CHOICES = (('high', 'High'), ('low', 'Low'), ('medium', 'Medium'))
	title = models.CharField(max_length = 200)
	description = models.TextField(null = True)
	created = models.DateTimeField(auto_now_add = True)
	priority = models.CharField(max_length = 20, choices = CHOICES)
	photo = models.ImageField(blank = True, upload_to = "%Y/%m/%d/photos/")

	def __str__(self):
		return self.title

	class Meta:
		ordering = ['-created']

	def get_absolute_url(self):
		return reverse('todo:detail', args = [self.pk])

account/forms.py
from django import forms


from django.contrib.auth.models import User

class UserRegisterForm(forms.ModelForm):
	password = forms.CharField(label = 'Password', widget = forms.PasswordInput)
	password2 = forms.CharField(label = 'Password again', widget = forms.PasswordInput)

	class Meta:
		model = User 
		fields = ['username', 'first_name', 'last_name', 'email']

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password'] != cd['password2']:
			raise forms.ValidationError('passwords do not match')
		return cd['password2'] 

todo_app/forms.py
from django import forms


from .models import Todo

class TodoForm(forms.ModelForm):
	class Meta:
		model = Todo
		fields = ['title', 'priority', 'description', 'photo']

account/views.py
from django.shortcuts import render
from django.contrib.auth.models import User


from .forms import UserRegisterForm

def register(request):
	if request.method == 'POST':
		user_form = UserRegisterForm(data = request.POST)
		if user_form.is_valid():
			new_user = user_form.save(commit = False)
			new_user.set_password(user_form.cleaned_data['password'])
			new_user.save()
			return render(request, 'account/register_done.html', {'new_user':new_user})
	else:
		user_form = UserRegisterForm()
	return render(request, 'account/register.html', {'user_form':user_form})

todo_app/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect

from .forms import TodoForm
from .models import Todo 

def home_page(request):
	todos = Todo.objects.all()
	context = {'todos':todos}
	template = 'todo_app/home_page.html'
	return render(request, template, context)

def todo_detail(request, todo_id):
	todo = get_object_or_404(Todo, pk = todo_id)
	context = {'todo':todo}
	template = 'todo_app/todo_view.html'
	return render(request, template, context)

def post_todo(request):
	if request.method == 'POST':
		form = TodoForm(data = request.POST, files = request.FILES)
		if form.is_valid():
			form.save()
			return render(request, 'todo_app/posted.html')
		else:
			return HttpResponse("Invalid submission")
	else:
		form = TodoForm()
	context = {'form':form}
	template = 'todo_app/post_todo.html'
	return render(request, template, context)

def edit_todo(request, todo_id):
	todo = get_object_or_404(Todo, pk = todo_id)
	if request.method == 'POST':
		form = TodoForm(data = request.POST, instance = todo, files = request.FILES)
		if form.is_valid():
			form.save()
			return redirect('todo:detail', todo.pk)
		else:
			return HttpResponse('Invalid submission')
	else:
		form = TodoForm(instance = todo)
	context = {'todo':todo, 'form':form}
	template = 'todo_app/post_todo.html'
	return render(request, template, context)

def delete_todo(request, todo_id):
	todo = get_object_or_404(Todo, pk = todo_id)
	todo.delete()
	context = {'todo':todo}
	template = 'todo_app/delete.html'
	return render(request, template, context)

todo_app/templates/base.html
{% load static %}
{% load crispy_forms_tags %}
{% load blog_tags %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"> 
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "todo_app/styles.css" %}">
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				{% block content %}
				{% endblock %}
			</div>
			{% if request.user.is_authenticated %}
			<div class="col-md-4">
				{% block side %}
					<br>
					<h3>Additions:</h3>
					<p><a href="{% url "todo:post" %}">add a todo?</a></p>
					<p>High priority todos:</p>
					<p id="list">{% high_priority 3 %}</p>	
					<p>Medium priority todos:</p>
					<p id="list">{% medium_priority 3 %}</p>
					<p>Low priority todos:</p>
					<p id="list">{% low_priority 3 %}</p>
				{% endblock %}
			</div>
			{% endif %}			
		</div>
	</div>
</body>
</html>

todo_app/templates/todo_app/delete.html
{% extends "base.html" %}

{% load static %}

{% block title %}
	delete
{% endblock %}

{% block content %}
	<br><br>
	<h3>Todo</h3>
	<br>
	<p>The post "{{ todo.title }}" will successfully deleted. <a href="{% url "todo:home" %}">Go back home?</a></p>
	<p><a href="{% url "todo:post" %}">add todo?</a></p>
{% endblock %}

todo_app/templates/todo_app/home_page.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
	home
{% endblock %}

{% block content %}
	<br>
	<h2>Todos: </h2>
	{% if request.user.is_authenticated %}
		<p><a href="{% url "account:logout-then-login" %}">logout</a></p>
	{% else %}
		<p><a href="{% url "account:login" %}"></a></p>
	{% endif %}
	{% if todos %}
		{% for todo in todos %}
			<h5><li><a href="{{ todo.get_absolute_url }}">{{ todo.title }}</a></li></h5>
			priority : <b>{{ todo.priority }}</b><br> 
			<p>{{ todo.description|truncatewords:10 }}</p><hr>
		{% endfor %}
	{% else %}
		<p>No todos yet. <a href="{% url "todo:post" %}">Start adding?</a></p>
	{% endif %}
{% endblock %}

todo_app/templates/todo_app/post_todo.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
	post a todo
{% endblock %}

{% block content %}
	<br><br>
	<h3>Todo</h3>
	<p>post a todo</p>
	<p><a href="{% url "todo:home" %}">go back home?</a></p>
	<br>
	<div class="row">
	<div class="col-md-4 offset-md-4">
	<form action="." method="POST", enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
		<button class="btn btn-primary btn-block">add</button>
	</form>
	</div>
	</div>
{% endblock %}

todo_app/templates/todo_app/posted.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% load static %}

{% block title %}
	success
{% endblock %}

{% block content %}
	<br><br>
	<h3>Todo</h3>
	<br>
	<p>Your todo has been successfully added. <a href="{% url "todo:home" %}">See todos?</a></p>
{% endblock %}

todo_app/templates/todo_app/priorities.html
{% if todos %}
	<ul>
		{% for todo in todos %}
			<li><a href="{{ todo.get_absolute_url }}">{{ todo.title }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>None</p>
{% endif %}

todo_app/templates/todo_app/priority_low.html
{% if todos %}
	<ul>
		{% for todo in todos %}
			<li><a href="{{ todo.get_absolute_url }}">{{ todo.title }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>None.</p>
{% endif %}

todo_app/templates/todo_app/priority_medium.html
{% if todos %}
	<ul>
		{% for todo in todos %}
			<li><a href="{{ todo.get_absolute_url }}">{{ todo.title }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>None.</p>
{% endif %}

todo_app/templates/todo_app/todo_view.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}
	{{ todo.title }}
{% endblock %}

{% block content %}
	<br><br>
	<h3>Todo</h3><br>
	{% if todo %}
		<h4>{{ todo.title }}</h4>
		<b>priority : {{ todo.priority }}</b>
		<p>{{ todo.description|linebreaks }}</p>
		<img src="{% if todo.photo %}{{ todo.photo.url }}{% else %}{% static "img/img.jpg" %}{% endif %}" width="250" height="250"><br><br>
		<a href="{% url "todo:edit" todo.pk %}">edit</a><br>
		<a style="color:red;" href="{% url "todo:delete" todo.pk %}">delete?</a><br>
	{% else %}
		<p>There's something wrong!</p>
	{% endif %}
	<a href="{% url "todo:home" %}">go back home?</a><hr>
{% endblock %}